<a href="https://colab.research.google.com/github/dragonaeve/cmpe255-spring19/blob/master/lab07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  
import warnings

warnings.filterwarnings('ignore')

def linear_svm():
    # download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
    # info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

    # load data
    bankdata = pd.read_csv("/tmp/bill_authentication.csv")  

    # see the data
    bankdata.shape  

    # see head
    bankdata.head()  

    # data processing
    X = bankdata.drop('Class', axis=1)  
    y = bankdata['Class']  

    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='linear')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))  

# Iris dataset  https://archive.ics.uci.edu/ml/datasets/iris4
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  
    return X_train, X_test, y_train, y_test
  
def polynomial_kernel(X_train, X_test, y_train, y_test):
    # TODO
    # Trains, predicts and evaluates the model
    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='poly', degree=8, gamma='auto')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Polynomial confusion matrix\n", confusion_matrix(y_test,y_pred))  
    print("Polynomial classification report\n", classification_report(y_test,y_pred))  

def gaussian_kernel(X_train, X_test, y_train, y_test):
    # TODO
    # Trains, predicts and evaluates the model
    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='rbf', gamma='auto')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Gaussian confusion matrix\n", confusion_matrix(y_test,y_pred))  
    print("Gaussian classification report\n", classification_report(y_test,y_pred))  

def sigmoid_kernel(X_train, X_test, y_train, y_test):
    # TODO
    # Trains, predicts and evaluates the model
    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='sigmoid', gamma='auto')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Sigmoid confusion matrix\n", confusion_matrix(y_test,y_pred))  
    print("Sigmoid classification report\n", classification_report(y_test,y_pred))  

def test():
    X_train, X_test, y_train, y_test = import_iris()
    polynomial_kernel(X_train, X_test, y_train, y_test)
    gaussian_kernel(X_train, X_test, y_train, y_test)
    sigmoid_kernel(X_train, X_test, y_train, y_test)

test()

Polynomial confusion matrix
 [[ 6  0  0]
 [ 0 10  2]
 [ 0  1 11]]
Polynomial classification report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.91      0.83      0.87        12
 Iris-virginica       0.85      0.92      0.88        12

      micro avg       0.90      0.90      0.90        30
      macro avg       0.92      0.92      0.92        30
   weighted avg       0.90      0.90      0.90        30

Gaussian confusion matrix
 [[ 6  0  0]
 [ 0 12  0]
 [ 0  0 12]]
Gaussian classification report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00        12

      micro avg       1.00      1.00      1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

